#!/bin/bash

# Velxio Development Script
# One-command build and run for local development
# Usage: ./build-dev.sh [command]
# Commands:
#   up       - Build (if needed) and start the container (default)
#   down     - Stop and remove the container
#   rebuild  - Force rebuild the image and start
#   clean    - Remove everything including volumes and rebuild
#   logs     - Follow container logs
#   shell    - Open a shell inside the running container
#   status   - Show container status

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
COMPOSE_FILE="docker-compose.prod.yml"
CONTAINER_NAME="velxio-app"
PORT="3080"

# Helper functions
print_header() {
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}======================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Check prerequisites
check_prerequisites() {
    print_header "Checking Prerequisites"

    # Check Docker
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    print_success "Docker is installed ($(docker --version))"

    # Check Docker Compose (prefer v1 for compatibility)
    if command -v docker-compose &> /dev/null; then
        DOCKER_COMPOSE="docker-compose"
        print_success "Docker Compose v1 is available"
    elif docker compose version &> /dev/null; then
        DOCKER_COMPOSE="docker compose"
        print_success "Docker Compose v2 is available"
    else
        print_error "Docker Compose is not installed"
        exit 1
    fi

    # Check if we're in the right directory
    if [ ! -f "$COMPOSE_FILE" ]; then
        print_error "$COMPOSE_FILE not found. Are you in the project root?"
        exit 1
    fi
    print_success "Project directory verified"
}

# Setup environment file
setup_env() {
    print_header "Setting up Environment"

    ENV_FILE="backend/.env"
    ENV_EXAMPLE="backend/.env.example"

    if [ -f "$ENV_FILE" ]; then
        print_info "Found existing $ENV_FILE"

        # Warn if using default SECRET_KEY
        if grep -q "SECRET_KEY=change-me" "$ENV_FILE" 2>/dev/null || \
           grep -q "SECRET_KEY=dev-" "$ENV_FILE" 2>/dev/null; then
            print_warning "Using default/insecure SECRET_KEY. Consider changing it for production."
        fi
    else
        print_info "Creating $ENV_FILE from defaults..."

        cat > "$ENV_FILE" << 'EOF'
# Velxio Backend Environment Configuration
# Generated by build-dev.sh for local development

# IMPORTANT: Change this to a secure random string for production!
# Generate with: openssl rand -hex 32
SECRET_KEY=dev-change-me-in-production-$(date +%s)

# Database URL (SQLite in container)
DATABASE_URL=sqlite+aiosqlite:////app/data/velxio.db

# Data directory for project files
DATA_DIR=/app/data

# Frontend URL (for CORS and redirects)
FRONTEND_URL=http://localhost:3080

# Google OAuth (optional - leave empty if not using)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:3080/api/auth/google/callback

# Set to true when serving over HTTPS
COOKIE_SECURE=false

# Token expiration (minutes)
ACCESS_TOKEN_EXPIRE_MINUTES=10080
EOF

        print_success "Created $ENV_FILE"
        print_info "Edit this file to customize settings (e.g., Google OAuth, SECRET_KEY)"
    fi

    # Create data directory
    mkdir -p data
    print_success "Data directory ready"
}

# Wait for container to be healthy
wait_for_healthy() {
    print_info "Waiting for container to be healthy..."
    local attempts=0
    local max_attempts=60

    while [ $attempts -lt $max_attempts ]; do
        if curl -sf http://localhost:$PORT/health > /dev/null 2>&1; then
            echo ""
            print_success "Container is healthy!"
            return 0
        fi

        attempts=$((attempts + 1))
        echo -ne "\r  Attempt $attempts/$max_attempts..."
        sleep 2
    done

    echo ""
    print_error "Container failed to become healthy within $((max_attempts * 2)) seconds"
    return 1
}

# Start containers
cmd_up() {
    check_prerequisites
    setup_env

    print_header "Starting Velxio"

    # Check if already running
    if $DOCKER_COMPOSE -f $COMPOSE_FILE ps | grep -q "$CONTAINER_NAME"; then
        print_info "Container is already running"
        print_info "Access the app at: http://localhost:$PORT"
        return 0
    fi

    print_info "Building and starting containers..."
    $DOCKER_COMPOSE -f $COMPOSE_FILE up -d

    if wait_for_healthy; then
        print_header "Velxio is Ready!"
        echo ""
        echo -e "  ${GREEN}App URL:${NC}      http://localhost:$PORT"
        echo -e "  ${GREEN}Health:${NC}       http://localhost:$PORT/health"
        echo -e "  ${GREEN}API Docs:${NC}     http://localhost:$PORT/api/docs"
        echo ""
        echo -e "  Useful commands:"
        echo -e "    ${YELLOW}./build-dev.sh logs${NC}     - Follow logs"
        echo -e "    ${YELLOW}./build-dev.sh shell${NC}    - Open container shell"
        echo -e "    ${YELLOW}./build-dev.sh down${NC}     - Stop the container"
        echo ""
    else
        print_error "Failed to start properly. Check logs with: ./build-dev.sh logs"
        exit 1
    fi
}

# Force rebuild
cmd_rebuild() {
    check_prerequisites
    setup_env

    print_header "Rebuilding Velxio"
    print_info "This will rebuild the Docker image..."

    $DOCKER_COMPOSE -f $COMPOSE_FILE down
    $DOCKER_COMPOSE -f $COMPOSE_FILE build --no-cache
    $DOCKER_COMPOSE -f $COMPOSE_FILE up -d

    if wait_for_healthy; then
        print_success "Rebuild complete! Access at http://localhost:$PORT"
    else
        print_error "Rebuild failed. Check logs."
        exit 1
    fi
}

# Clean build (remove volumes)
cmd_clean() {
    check_prerequisites

    print_header "Clean Rebuild"
    print_warning "This will remove all containers, images, and volumes!"
    echo ""
    read -p "Are you sure? [y/N] " -n 1 -r
    echo ""

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Cancelled"
        return 0
    fi

    print_info "Stopping and removing containers..."
    $DOCKER_COMPOSE -f $COMPOSE_FILE down -v --rmi all

    print_info "Removing data directory..."
    rm -rf data/

    print_success "Clean complete. Starting fresh build..."
    cmd_up
}

# Stop containers
cmd_down() {
    print_header "Stopping Velxio"
    $DOCKER_COMPOSE -f $COMPOSE_FILE down
    print_success "Container stopped"
}

# Show logs
cmd_logs() {
    if [ "$1" == "-f" ] || [ "$1" == "--follow" ] || [ -z "$1" ]; then
        print_info "Following logs (Ctrl+C to exit)..."
        $DOCKER_COMPOSE -f $COMPOSE_FILE logs -f
    else
        $DOCKER_COMPOSE -f $COMPOSE_FILE logs "$@"
    fi
}

# Open shell in container
cmd_shell() {
    if ! docker ps | grep -q "$CONTAINER_NAME"; then
        print_error "Container is not running. Start it first with: ./build-dev.sh up"
        exit 1
    fi

    print_info "Opening shell in container..."
    docker exec -it "$CONTAINER_NAME" /bin/bash
}

# Show status
cmd_status() {
    print_header "Velxio Status"

    if docker ps | grep -q "$CONTAINER_NAME"; then
        echo -e "${GREEN}Container Status: Running${NC}"
        docker ps | grep "$CONTAINER_NAME"

        if curl -sf http://localhost:$PORT/health > /dev/null 2>&1; then
            echo -e "${GREEN}Health Check: OK${NC}"
            curl -s http://localhost:$PORT/health | python3 -m json.tool 2>/dev/null || \
                curl -s http://localhost:$PORT/health
        else
            echo -e "${YELLOW}Health Check: Pending${NC}"
        fi

        echo ""
        echo "Access URLs:"
        echo "  http://localhost:$PORT"
    else
        echo -e "${YELLOW}Container Status: Not Running${NC}"
    fi
}

# Show help
cmd_help() {
    echo "Velxio Development Script"
    echo ""
    echo "Usage: ./build-dev.sh [command]"
    echo ""
    echo "Commands:"
    echo "  up       Start the container (build if needed) - default"
    echo "  down     Stop and remove the container"
    echo "  rebuild  Force rebuild the image and start"
    echo "  clean    Remove everything and rebuild from scratch"
    echo "  logs     Show container logs (use -f to follow)"
    echo "  shell    Open a shell inside the running container"
    echo "  status   Show container status and health"
    echo "  help     Show this help message"
    echo ""
    echo "Examples:"
    echo "  ./build-dev.sh              # Start velxio (same as 'up')"
    echo "  ./build-dev.sh up           # Start velxio"
    echo "  ./build-dev.sh rebuild      # Rebuild after code changes"
    echo "  ./build-dev.sh clean        # Clean slate (removes all data)"
    echo "  ./build-dev.sh logs -f      # Follow logs in real-time"
}

# Main
main() {
    COMMAND="${1:-up}"

    case "$COMMAND" in
        up|start)
            cmd_up
            ;;
        down|stop)
            cmd_down
            ;;
        rebuild)
            cmd_rebuild
            ;;
        clean)
            cmd_clean
            ;;
        logs)
            shift
            cmd_logs "$@"
            ;;
        shell|exec)
            cmd_shell
            ;;
        status)
            cmd_status
            ;;
        help|--help|-h)
            cmd_help
            ;;
        *)
            print_error "Unknown command: $COMMAND"
            cmd_help
            exit 1
            ;;
    esac
}

main "$@"
