/**
 * `component` template — a minimal plugin that registers a single component
 * with the host. Acts as the canonical "hello world" for plugin authors.
 *
 * `bundleHash` is intentionally NOT in the manifest — it lives on the
 * registry-side `InstalledPlugin` record. `velxio-plugin build` emits a
 * sibling `dist/integrity.json` carrying the SHA-256 the registry consumes.
 */

export interface TemplateFile {
  readonly path: string;
  readonly contents: string;
}

export function renderComponentTemplate(id: string): ReadonlyArray<TemplateFile> {
  return [
    { path: 'package.json', contents: renderPackageJson(id) },
    { path: 'manifest.json', contents: renderManifest(id) },
    { path: 'src/index.ts', contents: renderSrcIndex(id) },
    { path: 'tsconfig.json', contents: renderTsconfig() },
    { path: '.gitignore', contents: renderGitignore() },
    { path: 'README.md', contents: renderReadme(id) },
  ];
}

function renderPackageJson(id: string): string {
  return (
    JSON.stringify(
      {
        name: id,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: {
          build: 'velxio-plugin build',
          validate: 'velxio-plugin validate',
        },
        dependencies: {
          '@velxio/sdk': '^0.1.0',
        },
        devDependencies: {
          '@velxio/cli': '^0.1.0',
          typescript: '^5.9.0',
        },
      },
      null,
      2,
    ) + '\n'
  );
}

function renderManifest(id: string): string {
  return (
    JSON.stringify(
      {
        schemaVersion: 1,
        id,
        name: humanize(id),
        version: '0.1.0',
        sdkVersion: '^0.1.0',
        minVelxioVersion: '^0.1.0',
        author: { name: 'Your Name' },
        description:
          'A starter Velxio plugin generated by `velxio-plugin init` — replace this description with your own.',
        // 1x1 transparent PNG placeholder — replace with your real icon.
        icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        license: 'MIT',
        category: 'components',
        tags: [],
        type: ['component'],
        entry: './dist/bundle.mjs',
        permissions: ['components.register'],
        pricing: { model: 'free' },
        refundPolicy: 'none',
      },
      null,
      2,
    ) + '\n'
  );
}

function renderSrcIndex(id: string): string {
  return `import { defineComponent, definePlugin } from '@velxio/sdk';

/**
 * Sample component — replace this with your real metadata.
 * See https://velxio.dev/docs/plugins/components for the full schema.
 */
const myComponent = defineComponent({
  metadataId: '${id}-sample',
  displayName: '${humanize(id)} Sample',
  category: 'misc',
  pinLayout: [],
  defaultProps: {},
  render: () => null,
});

export default definePlugin({
  async activate(ctx) {
    ctx.subscriptions.add(ctx.components.register(myComponent));
    ctx.logger.info('${id} plugin activated');
  },
});
`;
}

function renderTsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          lib: ['ES2022', 'DOM'],
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          isolatedModules: true,
          noEmit: true,
        },
        include: ['src/**/*.ts'],
      },
      null,
      2,
    ) + '\n'
  );
}

function renderGitignore(): string {
  return ['node_modules/', 'dist/', '*.log', '.DS_Store', ''].join('\n');
}

function renderReadme(id: string): string {
  return `# ${humanize(id)}

A Velxio plugin scaffolded by \`velxio-plugin init\`.

## Develop

\`\`\`bash
npm install
npm run validate   # check manifest.json
npm run build      # bundle to dist/bundle.mjs
\`\`\`

## Publish

Once Velxio Pro accepts plugin submissions:

\`\`\`bash
npx velxio-plugin login
npx velxio-plugin publish
\`\`\`

See https://velxio.dev/docs/plugins for the full author guide.
`;
}

function humanize(id: string): string {
  return id
    .split('-')
    .map((word) => (word.length > 0 ? word[0]!.toUpperCase() + word.slice(1) : word))
    .join(' ');
}
